const orderActionType = {
  PLACE_ORDER_REQUEST: 'PLACE_ORDER_REQUEST',
  PLACE_ORDER_SUCCESS: 'PLACE_ORDER_SUCCESS',
  PLACE_ORDER_ERROR: 'PLACE_ORDER_ERROR',
  GET_ORDER_BY_ID_REQUEST: 'GET_ORDER_BY_ID_REQUEST',
  GET_ORDER_BY_ID_SUCCESS: 'GET_ORDER_BY_ID_SUCCESS',
  GET_ORDER_BY_ID_ERROR: 'GET_ORDER_BY_ID_ERROR',
};
export default orderActionType;
